[Debug] 2019-10-11 18:09:27.045304973 UTCLogNetworkStatement UDP Server started...
[Info] 2019-10-11 18:09:27.045492408 UTCLogNetworkStatement TCP Server started...
[Debug] 2019-10-11 18:09:33.312857985 UTCLogNetworkStatement newUdpConnection latest: 127.0.0.1:33775
[Info] 2019-10-11 18:09:33.313427323 UTCLogNetworkStatement readUdpSock: 
[Debug] Find_Node Message Recieved from : NodeEndPoint {nodeIp = "127.0.0.1", udpPort = 5680, tcpPort = 5680} @(arivi-p2p-0.1.0.0-BlfVYflqrilHIf47JKMj8n:Arivi.P2P.Kademlia.MessageHandler lib/Arivi/P2P/Kademlia/MessageHandler.hs:70:15)
[Debug] Add to kbucket called  @(arivi-p2p-0.1.0.0-BlfVYflqrilHIf47JKMj8n:Arivi.P2P.Kademlia.Kbucket lib/Arivi/P2P/Kademlia/Kbucket.hs:112:7)
[Debug] First_Element in respective kbucket @(arivi-p2p-0.1.0.0-BlfVYflqrilHIf47JKMj8n:Arivi.P2P.Kademlia.Kbucket lib/Arivi/P2P/Kademlia/Kbucket.hs:121:15)
[Debug] Kbucket after adding : [(0,[Peer {nodeID = "-\v6\228\175\CAN\SUB\130=<\238&\RS[\179f\t\DC2\154\202\185\143:\151\DC1\225\179\\\148\158U\152\137\223\183\175\&4\ACKA\130\SYNn\b\196x\155\175\185\222\&4\NAKo\179\143y\221aB\131\220e\211\240#", nodeEndPoint = NodeEndPoint {nodeIp = "127.0.0.1", udpPort = 5678, tcpPort = 5678}}]),(509,[Peer {nodeID = ";\230\213}ip\DC2\243Q\224\129o\176p`R'\178E\nQ\158[\186\225N\146\175\248\239-\245\240\GSZ\b~\203\rg\171\185\220\211\220\237k\249\STX\DEL\f\206\221\244\206\ETB4W(\168\a:\EM&", nodeEndPoint = NodeEndPoint {nodeIp = "127.0.0.1", udpPort = 5680, tcpPort = 5680}}])] @(arivi-p2p-0.1.0.0-BlfVYflqrilHIf47JKMj8n:Arivi.P2P.Kademlia.Kbucket lib/Arivi/P2P/Kademlia/Kbucket.hs:129:7)
[Info] 2019-10-11 18:09:33.314185897 UTCLogNetworkStatement readUdpSock: 
[Info] 2019-10-11 18:09:33.314923989 UTCLogNetworkStatement sendUdpMessage: Host: 127.0.0.1: Port: 33775: MsgLength: 146
[Info] 2019-10-11 18:09:38.323010872 UTCLogNetworkStatement sendUdpMessage: Host: 127.0.0.1: Port: 33775: MsgLength: 54
[Info] 2019-10-11 18:09:38.323206002 UTCLogNetworkStatement readUdpSock: 
[Info] 2019-10-11 18:10:08.348706564 UTCLogNetworkStatement readUdpSock: 
[Info] 2019-10-11 18:10:12.057512792 UTCLogNetworkStatement sendUdpMessage: Host: 127.0.0.1: Port: 33775: MsgLength: 50
[Info] 2019-10-11 18:10:12.060652524 UTCLogNetworkStatement readUdpSock: 
[Info] 2019-10-11 18:10:18.331187923 UTCLogNetworkStatement sendUdpMessage: Host: 127.0.0.1: Port: 33775: MsgLength: 54
[Info] 2019-10-11 18:10:18.331424509 UTCLogNetworkStatement readUdpSock: 
[Info] 2019-10-11 18:10:48.361847576 UTCLogNetworkStatement readUdpSock: 
[Info] 2019-10-11 18:10:48.362176039 UTCLogNetworkStatement readUdpSock: 
[Info] 2019-10-11 18:10:52.063700707 UTCLogNetworkStatement sendUdpMessage: Host: 127.0.0.1: Port: 33775: MsgLength: 50
[Info] 2019-10-11 18:10:52.066102783 UTCLogNetworkStatement readUdpSock: 
[Info] 2019-10-11 18:10:58.339737977 UTCLogNetworkStatement sendUdpMessage: Host: 127.0.0.1: Port: 33775: MsgLength: 54
[Info] 2019-10-11 18:10:58.340631259 UTCLogNetworkStatement readUdpSock: 
[Debug] 2019-10-11 18:11:08.464206796 UTCLogNetworkStatement Opening Connection to host 127.0.0.1 5680
[Info] 2019-10-11 18:11:08.465632624 UTCLogNetworkStatement readTcpSock: 
[Info] 2019-10-11 18:11:08.465752028 UTCLogNetworkStatement sendTcpMessage: Host: 127.0.0.1 
[Info] 2019-10-11 18:11:08.467355525 UTCLogNetworkStatement readTcpSock: 
[Info] 2019-10-11 18:11:08.506366102 UTCLogNetworkStatement sendTcpMessage: Host: 127.0.0.1 
[Info] 2019-10-11 18:11:08.508184336 UTCLogNetworkStatement readTcpSock: 
[Info] Exception occured: NetworkSocketExceptionat"CallStack (from HasCallStack):\n  logToF, called at ./Arivi/Utils/Logging.hs:61:5 in arivi-utils-0.1.0.0-D7sYDHhNIR4Fp85G6tmuz5:Arivi.Utils.Logging\n  withLocLogging, called at lib/Arivi/Network/ConnectionHandler.hs:208:7 in arivi-network-0.1.0.0-CmWbqBxaGB0FcYsCbK8lSI:Arivi.Network.ConnectionHandler\n  readTcpSock, called at lib/Arivi/Network/Instance.hs:88:26 in arivi-network-0.1.0.0-CmWbqBxaGB0FcYsCbK8lSI:Arivi.Network.Instance\n  $sel:recv:ConnectionHandle, called at lib/Arivi/Network/Types.hs:287:7 in arivi-network-0.1.0.0-CmWbqBxaGB0FcYsCbK8lSI:Arivi.Network.Types\n  readIncomingMessage, called at lib/Arivi/P2P/Handler.hs:81:13 in arivi-p2p-0.1.0.0-BlfVYflqrilHIf47JKMj8n:Arivi.P2P.Handler\n  readIncomingMessage, called at lib/Arivi/P2P/Handler.hs:81:13 in arivi-p2p-0.1.0.0-BlfVYflqrilHIf47JKMj8n:Arivi.P2P.Handler\n  readIncomingMessage, called at lib/Arivi/P2P/Connection.hs:37:29 in arivi-p2p-0.1.0.0-BlfVYflqrilHIf47JKMj8n:Arivi.P2P.Connection\n  createConnection, called at lib/Arivi/P2P/Connection.hs:57:33 in arivi-p2p-0.1.0.0-BlfVYflqrilHIf47JKMj8n:Arivi.P2P.Connection\n  getConnectionHandle, called at lib/Arivi/P2P/MessageHandler/NodeEndpoint.hs:104:29 in arivi-p2p-0.1.0.0-BlfVYflqrilHIf47JKMj8n:Arivi.P2P.MessageHandler.NodeEndpoint\n  issueRequest, called at lib/Arivi/P2P/RPC/Functions.hs:98:25 in arivi-p2p-0.1.0.0-BlfVYflqrilHIf47JKMj8n:Arivi.P2P.RPC.Functions\n  sendResourceRequest, called at lib/Arivi/P2P/RPC/Functions.hs:70:22 in arivi-p2p-0.1.0.0-BlfVYflqrilHIf47JKMj8n:Arivi.P2P.RPC.Functions\n  fetchResource, called at lib/AriviSecureRPC.hs:68:18 in main:AriviSecureRPC\n  goGetResource, called at lib/AriviSecureRPC.hs:90:21 in main:AriviSecureRPC\n  loopCall, called at app/Main.hs:153:17 in main:Main" @(arivi-network-0.1.0.0-CmWbqBxaGB0FcYsCbK8lSI:Arivi.Network.ConnectionHandler lib/Arivi/Network/ConnectionHandler.hs:208:7)
[Debug] network recv failed from readIncomingMessageNetworkSocketException";\230\213}ip\DC2\243Q\224\129o\176p`R'\178E\nQ\158[\186\225N\146\175\248\239-\245\240\GSZ\b~\203\rg\171\185\220\211\220\237k\249\STX\DEL\f\206\221\244\206\ETB4W(\168\a:\EM&" @(arivi-p2p-0.1.0.0-BlfVYflqrilHIf47JKMj8n:Arivi.P2P.MessageHandler.Utils lib/Arivi/P2P/MessageHandler/Utils.hs:26:38)
[Debug] 2019-10-11 18:23:04.848481232 UTCLogNetworkStatement UDP Server started...
[Info] 2019-10-11 18:23:04.848660876 UTCLogNetworkStatement TCP Server started...
[Debug] 2019-10-11 18:23:14.789369468 UTCLogNetworkStatement newUdpConnection latest: 127.0.0.1:57893
[Info] 2019-10-11 18:23:14.789925532 UTCLogNetworkStatement readUdpSock: 
[Debug] Find_Node Message Recieved from : NodeEndPoint {nodeIp = "127.0.0.1", udpPort = 5684, tcpPort = 5684} @(arivi-p2p-0.1.0.0-BlfVYflqrilHIf47JKMj8n:Arivi.P2P.Kademlia.MessageHandler lib/Arivi/P2P/Kademlia/MessageHandler.hs:70:15)
[Debug] Add to kbucket called  @(arivi-p2p-0.1.0.0-BlfVYflqrilHIf47JKMj8n:Arivi.P2P.Kademlia.Kbucket lib/Arivi/P2P/Kademlia/Kbucket.hs:112:7)
[Debug] First_Element in respective kbucket @(arivi-p2p-0.1.0.0-BlfVYflqrilHIf47JKMj8n:Arivi.P2P.Kademlia.Kbucket lib/Arivi/P2P/Kademlia/Kbucket.hs:121:15)
[Debug] Kbucket after adding : [(0,[Peer {nodeID = "-\v6\228\175\CAN\SUB\130=<\238&\RS[\179f\t\DC2\154\202\185\143:\151\DC1\225\179\\\148\158U\152\137\223\183\175\&4\ACKA\130\SYNn\b\196x\155\175\185\222\&4\NAKo\179\143y\221aB\131\220e\211\240#", nodeEndPoint = NodeEndPoint {nodeIp = "127.0.0.1", udpPort = 5682, tcpPort = 5682}}]),(509,[Peer {nodeID = ";\230\213}ip\DC2\243Q\224\129o\176p`R'\178E\nQ\158[\186\225N\146\175\248\239-\245\240\GSZ\b~\203\rg\171\185\220\211\220\237k\249\STX\DEL\f\206\221\244\206\ETB4W(\168\a:\EM&", nodeEndPoint = NodeEndPoint {nodeIp = "127.0.0.1", udpPort = 5684, tcpPort = 5684}}])] @(arivi-p2p-0.1.0.0-BlfVYflqrilHIf47JKMj8n:Arivi.P2P.Kademlia.Kbucket lib/Arivi/P2P/Kademlia/Kbucket.hs:129:7)
[Info] 2019-10-11 18:23:14.79063502 UTCLogNetworkStatement readUdpSock: 
[Info] 2019-10-11 18:23:14.791302578 UTCLogNetworkStatement sendUdpMessage: Host: 127.0.0.1: Port: 57893: MsgLength: 146
[Info] 2019-10-11 18:23:19.798182704 UTCLogNetworkStatement sendUdpMessage: Host: 127.0.0.1: Port: 57893: MsgLength: 54
[Info] 2019-10-11 18:23:19.799057311 UTCLogNetworkStatement readUdpSock: 
[Info] 2019-10-11 18:23:49.802645804 UTCLogNetworkStatement readUdpSock: 
[Info] 2019-10-11 18:23:49.859387397 UTCLogNetworkStatement sendUdpMessage: Host: 127.0.0.1: Port: 57893: MsgLength: 50
[Info] 2019-10-11 18:23:49.861475743 UTCLogNetworkStatement readUdpSock: 
[Debug] 2019-10-11 18:23:54.07690695 UTCLogNetworkStatement Opening Connection to host 127.0.0.1 5684
[Info] 2019-10-11 18:23:54.0779042 UTCLogNetworkStatement readTcpSock: 
[Info] 2019-10-11 18:23:54.07796892 UTCLogNetworkStatement sendTcpMessage: Host: 127.0.0.1 
[Info] 2019-10-11 18:23:54.078705303 UTCLogNetworkStatement readTcpSock: 
[Info] 2019-10-11 18:23:54.119115714 UTCLogNetworkStatement sendTcpMessage: Host: 127.0.0.1 
[Info] 2019-10-11 18:23:54.119906008 UTCLogNetworkStatement readTcpSock: 
[Info] 2019-10-11 18:23:59.806409098 UTCLogNetworkStatement sendUdpMessage: Host: 127.0.0.1: Port: 57893: MsgLength: 54
[Info] 2019-10-11 18:23:59.807319225 UTCLogNetworkStatement readUdpSock: 
[Info] 2019-10-11 18:24:04.925238762 UTCLogNetworkStatement sendTcpMessage: Host: 127.0.0.1 
[Info] 2019-10-11 18:24:04.925869771 UTCLogNetworkStatement readTcpSock: 
[Info] 2019-10-11 18:24:04.96881085 UTCLogNetworkStatement sendTcpMessage: Host: 127.0.0.1 
[Info] 2019-10-11 18:24:04.969746488 UTCLogNetworkStatement readTcpSock: 
[Info] Exception occured: NetworkSocketExceptionat"CallStack (from HasCallStack):\n  logToF, called at ./Arivi/Utils/Logging.hs:61:5 in arivi-utils-0.1.0.0-D7sYDHhNIR4Fp85G6tmuz5:Arivi.Utils.Logging\n  withLocLogging, called at lib/Arivi/Network/ConnectionHandler.hs:208:7 in arivi-network-0.1.0.0-CmWbqBxaGB0FcYsCbK8lSI:Arivi.Network.ConnectionHandler\n  readTcpSock, called at lib/Arivi/Network/Instance.hs:88:26 in arivi-network-0.1.0.0-CmWbqBxaGB0FcYsCbK8lSI:Arivi.Network.Instance\n  $sel:recv:ConnectionHandle, called at lib/Arivi/Network/Types.hs:287:7 in arivi-network-0.1.0.0-CmWbqBxaGB0FcYsCbK8lSI:Arivi.Network.Types\n  readIncomingMessage, called at lib/Arivi/P2P/Handler.hs:81:13 in arivi-p2p-0.1.0.0-BlfVYflqrilHIf47JKMj8n:Arivi.P2P.Handler\n  readIncomingMessage, called at lib/Arivi/P2P/Handler.hs:81:13 in arivi-p2p-0.1.0.0-BlfVYflqrilHIf47JKMj8n:Arivi.P2P.Handler\n  readIncomingMessage, called at lib/Arivi/P2P/Handler.hs:81:13 in arivi-p2p-0.1.0.0-BlfVYflqrilHIf47JKMj8n:Arivi.P2P.Handler\n  readIncomingMessage, called at lib/Arivi/P2P/Handler.hs:81:13 in arivi-p2p-0.1.0.0-BlfVYflqrilHIf47JKMj8n:Arivi.P2P.Handler\n  readIncomingMessage, called at lib/Arivi/P2P/Connection.hs:37:29 in arivi-p2p-0.1.0.0-BlfVYflqrilHIf47JKMj8n:Arivi.P2P.Connection\n  createConnection, called at lib/Arivi/P2P/Connection.hs:57:33 in arivi-p2p-0.1.0.0-BlfVYflqrilHIf47JKMj8n:Arivi.P2P.Connection\n  getConnectionHandle, called at lib/Arivi/P2P/MessageHandler/NodeEndpoint.hs:104:29 in arivi-p2p-0.1.0.0-BlfVYflqrilHIf47JKMj8n:Arivi.P2P.MessageHandler.NodeEndpoint\n  issueRequest, called at lib/Arivi/P2P/RPC/Functions.hs:98:25 in arivi-p2p-0.1.0.0-BlfVYflqrilHIf47JKMj8n:Arivi.P2P.RPC.Functions\n  sendResourceRequest, called at lib/Arivi/P2P/RPC/Functions.hs:70:22 in arivi-p2p-0.1.0.0-BlfVYflqrilHIf47JKMj8n:Arivi.P2P.RPC.Functions\n  fetchResource, called at lib/AriviSecureRPC.hs:68:18 in main:AriviSecureRPC\n  goGetResource, called at lib/AriviSecureRPC.hs:90:21 in main:AriviSecureRPC\n  loopCall, called at lib/AriviSecureRPC.hs:92:9 in main:AriviSecureRPC\n  loopCall, called at lib/AriviSecureRPC.hs:92:9 in main:AriviSecureRPC\n  loopCall, called at app/Main.hs:153:17 in main:Main" @(arivi-network-0.1.0.0-CmWbqBxaGB0FcYsCbK8lSI:Arivi.Network.ConnectionHandler lib/Arivi/Network/ConnectionHandler.hs:208:7)
[Debug] network recv failed from readIncomingMessageNetworkSocketException";\230\213}ip\DC2\243Q\224\129o\176p`R'\178E\nQ\158[\186\225N\146\175\248\239-\245\240\GSZ\b~\203\rg\171\185\220\211\220\237k\249\STX\DEL\f\206\221\244\206\ETB4W(\168\a:\EM&" @(arivi-p2p-0.1.0.0-BlfVYflqrilHIf47JKMj8n:Arivi.P2P.MessageHandler.Utils lib/Arivi/P2P/MessageHandler/Utils.hs:26:38)
